/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package loadbalancer

import (
	"bytes"
	"strings"
	"text/template"
	"fmt"

	"sigs.k8s.io/kind/pkg/errors"
)

// ConfigData is supplied to the loadbalancer config template
type ConfigData struct {
	ControlPlanePort int
	BackendServers   map[string]string
	IPv6             bool
}

// DefaultConfigTemplate is the loadbalancer config template
const DefaultConfigTemplate = `# generated by kind
static_resources:
  listeners:
  - name: control-plane-listener-ipv4
    address:
      socket_address:
        address: "0.0.0.0"
        port_value: {{ .ControlPlanePort }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: kube_apiserver
          cluster: kube_apiservers
  {{- if .IPv6 }}
  - name: control-plane-listener-ipv6
    address:
      socket_address:
        address: "::"
        port_value: {{ .ControlPlanePort }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: kube_apiserver
          cluster: kube_apiservers
  {{- end }}
  clusters:
  - name: kube_apiservers
    type: STRICT_DNS
    connect_timeout: 5s
    lb_policy: ROUND_ROBIN
    dns_lookup_family: AUTO
    dns_refresh_rate: 30s
    respect_dns_ttl: true
    circuit_breakers:
      thresholds:
      - priority: DEFAULT
        max_connections: 100000
        max_pending_requests: 20000
        max_requests: 100000
    load_assignment:
      cluster_name: kube_apiservers
      endpoints:
      - lb_endpoints:
        {{- range $server, $address := .BackendServers }}
	{{- $hp := hostPort $address }}
        - endpoint:
            address:
              socket_address:
                address: {{ $hp.host }}
                port_value: {{ $hp.port }}
        {{- end }}

    health_checks:
    - timeout: 5s
      interval: 10s
      unhealthy_threshold: 3
      healthy_threshold: 1
      http_health_check:
        path: /livez
        expected_statuses:
        - start: 200
          end: 399
        codec_client_type: HTTP1
admin:
  access_log_path: /dev/stdout
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
`

func hostPort(addr string) (map[string]string, error) {
	parts := strings.Split(addr, ":")
	if len(parts) != 2 {
		return nil, fmt.Errorf("expected host:port, got %q", addr)
	}
	return map[string]string{"host": parts[0], "port": parts[1]}, nil
}

// Config returns a kubeadm config generated from config data, in particular
// the kubernetes version
func Config(data *ConfigData) (config string, err error) {
	funcs := template.FuncMap{
		"hostPort": hostPort,
	}
	t, err := template.New("envoy-config").Funcs(funcs).Parse(DefaultConfigTemplate)
	if err != nil {
		return "", errors.Wrap(err, "failed to parse config template")
	}
	
  // execute the template
	var buff bytes.Buffer
	if err := t.Execute(&buff, data); err != nil {
		return "", errors.Wrap(err, "error executing config template")
	}
	configStr := buff.String()
	fmt.Println("DEBUG GENERATED CONFIG:\n", configStr)
	return configStr, nil
}
